### ISSUE TITLE
Processing feedback

### ISSUE THREAD

**Issue by jgalvan** [Irvel/Actionable-Screenshots#1]
Provide user with feedback of progress for processing new screenshots.

![simulator screen shot - iphone 8 - 2017-10-22 at 22 19 44](https://user-images.githubusercontent.com/6772675/31871052-1f1e29cc-b777-11e7-977f-a18e045adcd3.png)

**Comment by Irvel** [comment]
Fixed as of [f6df33a](https://github.com/Irvel/Actionable-Screenshots/commit/f6df33ae58f107656eb8690f19716d4a37afbf6c)
